[package]
name        = "flix-invaders"
description = "A Flix creative-coding pilot on Swing and Java2D."
version     = "0.2.0"
flix        = "0.75.2"
license     = "MIT"
authors     = ["Werner Stein <werner.stein@gmail.com>"]
